Repository LEAP-2024-1C/company_kpi_salary_calculate_app, pull requests merged in 2024-10, with the labels that each got.

#5 frontend: create sign in page
  frontend/src/app/page.tsx
Labels: enhancement

#11 logup controller nemev
  backend/src/controllers/auth.controller.ts
Labels: enhancement

#18 login front
  frontend/src/app/page.tsx
Labels: enhancement

#21 admin:create employee
  admin/.env
  admin/app/dashboard/product/[productId]/page.tsx
  admin/components/forms/employee-form.tsx
  admin/components/forms/product-form.tsx
  admin/lib/utils.ts
  admin/package-lock.json
  admin/package.json
Labels: enhancement

#23 admin: create employee
  admin/components/forms/employee-form.tsx
  admin/components/tables/user-tables/client.tsx
  admin/components/ui/data-table.tsx
Labels: enhancement

#25 15 login frontend A
  frontend/package-lock.json
  frontend/package.json
  frontend/public/images/defaultProfilePic.jpg
  frontend/src/app/dashboard/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/app/task-detail/page.tsx
  frontend/src/components/header/drowdown.tsx
  frontend/src/components/header/header.tsx
  frontend/src/components/task-card.tsx
  frontend/src/components/taskDetailModal.tsx
  frontend/src/components/ui/sidebar.tsx
  frontend/tailwind.config.ts
Labels: enhancement

#24 backend: auth controller done
  backend/package-lock.json
  backend/package.json
  backend/src/config/db.ts
  backend/src/controllers/auth-controller.ts
  backend/src/controllers/auth.controller.ts
  backend/src/controllers/cat-controller.ts
  backend/src/index.ts
  backend/src/middlewares/auth.ts
  backend/src/models/category.model.ts
  backend/src/models/employee.model.ts
  backend/src/models/product.model.ts
  backend/src/routes/authRoute.ts
  backend/src/routes/catRoute.ts
  backend/src/utils/decodeToken.ts
  backend/src/utils/generateToken.ts
Labels: enhancement

#27 api_url
  admin/app/dashboard/user/[userId]/page.tsx
  admin/components/forms/employee-form.tsx
  backend/package-lock.json
  backend/src/controllers/auth-controller.ts
  backend/src/routes/authRoute.ts
  frontend/src/app/page.tsx
  frontend/src/lib/utils.ts
Labels: enhancement

#29 create, get employees
  admin/app/dashboard/user/page.tsx
  admin/components/tables/user-tables/client.tsx
  admin/components/ui/data-table.tsx
  admin/constants/data.ts
  backend/src/controllers/auth-controller.ts
  backend/src/routes/authRoute.ts
Labels: documentation

#30 backend:10 auth controller hiih
  admin/app/api/auth/[...nextauth]/route.ts
  admin/app/api/uploadthing/core.ts
  admin/app/api/uploadthing/route.ts
  admin/app/layout.tsx
  admin/auth.config.ts
  admin/auth.ts
  admin/components/layout/providers.tsx
  admin/middleware.ts
  backend/src/controllers/cat-controller.ts
Labels: enhancement

#32 admin: project uusgeh
  admin/.gitignore
  admin/app/dashboard/category/page.tsx
  admin/app/dashboard/example/page.tsx
  admin/app/dashboard/product/[productId]/page.tsx
  admin/app/dashboard/product/page.tsx
  admin/components/forms/category-form.tsx
  admin/components/forms/product-form.tsx
  admin/components/tables/category-tables/category-table.tsx
  admin/constants/data.ts
  backend/src/controllers/auth-controller.ts
  backend/src/controllers/cat-controller.ts
  backend/src/models/category.model.ts
  backend/src/routes/authRoute.ts
Labels: bug, enhancement

#39 15 login frontend
  .DS_Store
  backend/src/controllers/auth-controller.ts
  backend/src/routes/authRoute.ts
  frontend/src/app/(auth)/salaryCalculator/page.tsx
  frontend/src/app/(auth)/userInfo/page.tsx
  frontend/src/app/dashboard/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/app/task-detail/page.tsx
  frontend/src/components/header/drowdown.tsx
  frontend/src/components/header/header.tsx
  frontend/src/components/task-card.tsx
  frontend/src/components/taskDetailModal.tsx
  frontend/src/context/taskTrack-provider.tsx
  frontend/src/context/user-provider.tsx
  frontend/src/utils/interfaces.ts
Labels: enhancement

#40 10 auth controller hiih
  admin/.env
  admin/app/dashboard/example/page.tsx
  admin/app/dashboard/layout.tsx
  admin/app/dashboard/product/[productId]/page.tsx
  admin/app/dashboard/project/page.tsx
  admin/app/dashboard/test/page.tsx
  admin/components/forms/product-form.tsx
  admin/constants/data.ts
Labels: enhancement

#37 31 admin add projects
  admin/app/dashboard/project/[projectId]/page.tsx
  admin/app/dashboard/project/page.tsx
  admin/components/icons.tsx
  admin/components/tables/project-tables/cell-action.tsx
  admin/components/tables/project-tables/client.tsx
  admin/components/ui/data-table2.tsx
  admin/constants/data.ts
Labels: enhancement

#44 employee tasks
  admin/app/dashboard/employee-task/page.tsx
  admin/components/ui/data-table2.tsx
Labels: enhancement

#46 product uusgev
  admin/app/dashboard/projectsExample/page.tsx
  admin/components/forms/product-form.tsx
  admin/constants/data.ts
  backend/src/controllers/product-contoller.ts
  backend/src/index.ts
  backend/src/models/components.model.ts
  backend/src/models/product.model.ts
  backend/src/routes/proRoute.ts
Labels: enhancement

#47 get
  admin/app/dashboard/employee-task/page.tsx
  admin/components/forms/employee-form.tsx
Labels: enhancement

#49 10 auth controller hiih
  backend/src/controllers/product-contoller.ts
Labels: enhancement

#52 product stat controller hiiv
  admin/app/dashboard/product/[productId]/page.tsx
  admin/components/forms/product-form.tsx
  admin/constants/data.ts
  admin/next.config.js
  backend/src/controllers/cat-controller.ts
  backend/src/controllers/product-contoller.ts
  backend/src/models/category.model.ts
  backend/src/models/components.model.ts
  backend/src/models/product.model.ts
  backend/src/routes/proRoute.ts
Labels: enhancement
