Repository LEAP-2024-1C/company_kpi_salary_calculate_app, pull requests merged in 2024-11, with the labels that each got.

#53 43 category bolon product page design ynzlah
  admin/components/forms/category-form.tsx
Labels: documentation

#51 48 admin project get
  admin/app/dashboard/employee-task/page.tsx
  admin/app/dashboard/project/[projectId]/page.tsx
  admin/app/dashboard/project/page.tsx
  admin/components/ui/data-table2.tsx
  admin/constants/data.ts
  backend/src/controllers/product-contoller.ts
  backend/src/models/category.model.ts
  backend/src/models/components.model.ts
  backend/src/models/product.model.ts
Labels: enhancement

#55 category interface id uusgesen
  admin/components/tables/category-tables/category-table.tsx
  admin/components/tables/category-tables/cell-action.tsx
  admin/constants/data.ts
Labels: documentation

#56 change dashboard
  admin/app/dashboard/page.tsx
  admin/app/dashboard/project/page.tsx
  admin/components/tables/project-tables/client.tsx
  admin/components/ui/data-table2.tsx
  frontend/src/app/(auth)/forgerpass/email/page.tsx
  frontend/src/app/(auth)/forgerpass/newpass/page.tsx
  frontend/src/app/(auth)/forgerpass/otp/page.tsx
  frontend/src/app/page.tsx
Labels: enhancement

#58 43 category page dotorhi zasvar
  admin/app/dashboard/category/page.tsx
  admin/app/dashboard/employee-task/page.tsx
  admin/app/dashboard/product/[productId]/page.tsx
  admin/components/forms/category-form.tsx
  admin/components/forms/product-form.tsx
  admin/components/inputs/category-inputs.tsx
  admin/components/tables/category-tables/category-table.tsx
  admin/components/tables/category-tables/cell-action.tsx
  admin/constants/data.ts
  backend/src/controllers/cat-controller.ts
  backend/src/routes/catRoute.ts
Labels: documentation

#60 product controller uurcluv
  admin/components/forms/product-form.tsx
  admin/constants/data.ts
  backend/src/controllers/cat-controller.ts
  backend/src/controllers/product-contoller.ts
  backend/src/models/category.model.ts
  backend/src/models/components.model.ts
  backend/src/routes/proRoute.ts
Labels: enhancement

#61 front:t ask haruulah +savedTasks
  backend/src/controllers/product-contoller.ts
  backend/src/controllers/savedTasks-controller.ts
  backend/src/index.ts
  backend/src/models/savedTasks.model.ts
  backend/src/routes/proRoute.ts
  backend/src/routes/savedRoute.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/[id]/page.tsx
  frontend/src/app/dashboard/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/task-detail/page.tsx
  frontend/src/components/productDetailModal.tsx
  frontend/src/components/savedTasksCard.tsx
  frontend/src/components/status.tsx
  frontend/src/components/task-card.tsx
  frontend/src/components/taskDetailModal.tsx
  frontend/src/components/ui/button.tsx
  frontend/src/context/product-provider.tsx
  frontend/src/context/task-provider.tsx
  frontend/src/context/taskTrack-provider.tsx
  frontend/src/utils/interfaces.ts
Labels: enhancement

#63 save product model uusgev, postman turshiv
  backend/src/controllers/auth-controller.ts
  backend/src/controllers/product-contoller.ts
  backend/src/controllers/savedTasks-controller.ts
  backend/src/index.ts
  backend/src/models/savedTasks.model.ts
  backend/src/routes/proRoute.ts
  backend/src/routes/savedRoute.ts
  frontend/.gitignore
Labels: enhancement

#66 36 front product haruulah
  frontend/src/app/[id]/page.tsx
  frontend/src/app/page.tsx
  frontend/src/components/productDetailModal.tsx
  frontend/src/components/savedTasksCard.tsx
  frontend/src/utils/interfaces.ts
Labels: enhancement

#68 save
  backend/src/controllers/auth-controller.ts
  backend/src/controllers/product-contoller.ts
  backend/src/models/product.model.ts
  frontend/src/app/(auth)/salaryCalculator/page.tsx
  frontend/src/app/[id]/page.tsx
  frontend/src/components/productDetailModal.tsx
  frontend/src/components/savedTasksCard.tsx
  frontend/src/components/task-card.tsx
  frontend/src/context/task-provider.tsx
  frontend/src/utils/interfaces.ts
Labels: enhancement

#69 43 category bolon product page design ynzlah
  admin/components/tables/category-tables/category-table.tsx
  admin/components/tables/category-tables/cell-action.tsx
  backend/src/controllers/cat-controller.ts
  backend/src/routes/catRoute.ts
Labels: documentation

#67 54 admin employee data stat
  backend/src/controllers/auth-controller.ts
  backend/src/routes/authRoute.ts
  backend/src/utils/generateHtmlTemplate.ts
  backend/src/utils/send-email.ts
  frontend/src/app/(auth)/forgerpass/email/page.tsx
  frontend/src/app/(auth)/forgerpass/newpass/page.tsx
  frontend/src/app/(auth)/forgerpass/otp/page.tsx
  frontend/src/app/(auth)/forgetpass/email/page.tsx
  frontend/src/app/(auth)/forgetpass/newpass/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/components/ui/form.tsx
  frontend/src/utils/validationSchema.ts
Labels: duplicate, enhancement

#75 employee can choose task completed
  admin/.gitignore
  backend/src/controllers/auth-controller.ts
  backend/src/controllers/cat-controller.ts
  backend/src/controllers/comp-controller.ts
  backend/src/controllers/product-contoller.ts
  backend/src/controllers/savedTasks-controller.ts
  backend/src/index.ts
  backend/src/models/components.model.ts
  backend/src/models/product.model.ts
  backend/src/models/savedTasks.model.ts
  backend/src/routes/compRoute.ts
  backend/src/routes/savedRoute.ts
  backend/test.js
  frontend/next.config.mjs
  frontend/src/app/[id]/page.tsx
  frontend/src/app/dashboard/page.tsx
  frontend/src/components/productDetailModal.tsx
  frontend/src/components/task-card.tsx
  frontend/src/context/product-provider.tsx
  frontend/src/context/user-provider.tsx
  frontend/src/utils/interfaces.ts
Labels: bug

#77 72 userinfo form
  backend/src/controllers/auth-controller.ts
  backend/src/controllers/savedTasks-controller.ts
  backend/src/routes/authRoute.ts
  frontend/src/app/(auth)/salaryCalculator/page.tsx
  frontend/src/app/(auth)/userInfo/page.tsx
  frontend/src/app/dashboard/page.tsx
  frontend/src/app/edit-profile/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/components/header/drowdown.tsx
  frontend/src/components/header/header.tsx
  frontend/src/components/loader/loader.module.css
  frontend/src/components/loader/loader.tsx
  frontend/src/components/ui/button.tsx
  frontend/src/utils/interfaces.ts
  frontend/src/utils/validationSchema.ts
Labels: enhancement

#80 choose task done
  backend/src/controllers/comp-controller.ts
  backend/src/controllers/savedTasks-controller.ts
  backend/src/models/components.model.ts
  backend/src/models/savedTasks.model.ts
  backend/src/routes/compRoute.ts
  backend/src/routes/savedRoute.ts
  frontend/src/app/[id]/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/components/productDetailModal.tsx
  frontend/src/context/user-provider.tsx
Labels: enhancement

#82 78 update components
  backend/src/controllers/comp-controller.ts
  frontend/src/app/(auth)/forgetpass/newpass/page.tsx
  frontend/src/app/[id]/page.tsx
  frontend/src/app/edit-profile/page.tsx
  frontend/src/components/auth/recoverPass/recoverpass.tsx
  frontend/src/components/header/drowdown.tsx
  frontend/src/components/header/header.tsx
  frontend/src/components/productDetailModal.tsx
  frontend/src/components/ui/calendar.tsx
  frontend/src/components/ui/chart.tsx
  frontend/src/context/task-provider.tsx
  frontend/src/utils/interfaces.ts
Labels: documentation

#83 admin can change task status
  admin/.env
  admin/.gitignore
  admin/app/dashboard/employee-task/[id]/page.tsx
  admin/app/dashboard/employee-task/page.tsx
  admin/app/dashboard/page.tsx
  admin/app/dashboard/product/[productId]/page.tsx
  admin/components/tables/project-tables/client.tsx
  admin/components/ui/data-table2.tsx
  admin/constants/data.ts
  admin/env.example.txt
  backend/src/controllers/comp-controller.ts
  backend/src/controllers/product-contoller.ts
  backend/src/controllers/savedTasks-controller.ts
  backend/src/index.ts
  backend/src/routes/compRoute.ts
  backend/src/routes/taskRoute.ts
Labels: enhancement

#84 79 saved product haruulah
  frontend/public/images/clothing.logo.jpg
  frontend/src/app/(auth)/layout.tsx
  frontend/src/app/[id]/layout.tsx
  frontend/src/app/dashboard/layout.tsx
  frontend/src/app/edit-profile/layout.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/salaryCalculator/layout.tsx
  frontend/src/app/salaryCalculator/page.tsx
  frontend/src/components/header/header.tsx
  frontend/src/components/task-card.tsx
Labels: enhancement

#85 70 category dotorh task edit bolon delete button hiij duusav
  admin/app/dashboard/category/new/page.tsx
  admin/app/dashboard/category/page.tsx
  admin/app/dashboard/category/update/[categoryId]/page.tsx
  admin/app/dashboard/layout.tsx
  admin/components/forms/category-form.tsx
  admin/components/forms/category-update-form.tsx
  admin/components/forms/product-form.tsx
  admin/components/inputs/category-inputs.tsx
  admin/components/tables/category-tables/category-table.tsx
  admin/components/tables/category-tables/cell-action.tsx
  admin/context/admin-context.tsx
  backend/src/controllers/cat-controller.ts
  backend/src/routes/catRoute.ts
Labels: documentation

#89 employee can change task status
  backend/src/controllers/comp-controller.ts
  backend/src/controllers/savedTasks-controller.ts
  backend/src/routes/taskRoute.ts
  frontend/src/app/(auth)/salaryCalculator/page.tsx
  frontend/src/app/(auth)/salaryCalculatorex/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/salaryCalculator/page.tsx
  frontend/src/components/header/header.tsx
  frontend/src/components/productDetailModal.tsx
  frontend/src/components/task-card.tsx
  frontend/src/utils/interfaces.ts
Labels: enhancement

#96 86 admin category dotor procedure nemeh
  admin/app/dashboard/category/page.tsx
  admin/app/dashboard/product/page.tsx
  admin/components/forms/category-form.tsx
  admin/components/forms/product-form.tsx
  admin/components/inputs/category-inputs.tsx
  admin/components/tables/category-tables/category-table.tsx
  admin/components/tables/product-tables/cell-action.tsx
  admin/components/tables/product-tables/product-table.tsx
  admin/constants/data.ts
  backend/src/controllers/cat-controller.ts
  backend/src/controllers/product-contoller.ts
  backend/src/routes/proRoute.ts
Labels: documentation

#98 fix pproduct page
  admin/components/forms/category-update-form.tsx
  admin/components/forms/product-form.tsx
  admin/components/tables/product-tables/product-table.tsx
Labels: documentation

#100 90 admin signup
  admin/app/dashboard/employee-task/[id]/page.tsx
  admin/app/dashboard/user/[userId]/page.tsx
  admin/components/tables/user-tables/cell-action.tsx
  admin/components/ui/data-table.tsx
  admin/components/ui/data-table2.tsx
  admin/constants/data.ts
  backend/src/controllers/auth-controller.ts
  backend/src/controllers/savedTasks-controller.ts
  frontend/src/components/auth/recoverPass/recoverpass.tsx
Labels: enhancement

#102 deploy hiihed beldev
  admin/app/(auth)/(signin)/page.tsx
  admin/app/dashboard/test/page.tsx
  admin/components/file-upload.tsx
  admin/components/forms/employee-form.tsx
  admin/components/ui/data-table2.tsx
  backend/src/controllers/auth-controller.ts
  backend/src/controllers/cat-controller.ts
  backend/src/controllers/comp-controller.ts
  backend/src/controllers/savedTasks-controller.ts
  frontend/.eslintrc.json
  frontend/src/app/dashboard/page.tsx
  frontend/src/app/edit-profile/page.tsx
  frontend/src/app/my-tasks/page.tsx
  frontend/src/app/page.tsx
  frontend/src/components/footer/footer.tsx
  frontend/src/components/salary-main/resultChart.tsx
  frontend/src/components/salary-main/salaryChart.tsx
  frontend/src/components/status.tsx
  frontend/src/components/task-card.tsx
  frontend/src/components/ui/chart.tsx
Labels: enhancement

#110 design
  frontend/src/app/(auth)/forgetpass/email/page.tsx
Labels: enhancement

#112 zasvar hiiv
  admin/app/dashboard/employee-task/[id]/page.tsx
  admin/app/dashboard/page.tsx
  admin/app/dashboard/user/[userId]/page.tsx
  admin/components/forms/category-form.tsx
  admin/components/forms/employee-form.tsx
  admin/components/tables/project-tables/client.tsx
  admin/components/tables/user-tables/client.tsx
  admin/components/ui/data-table.tsx
  admin/components/ui/data-table2.tsx
  frontend/src/components/footer/footer.tsx
  frontend/src/components/header/header.tsx
Labels: documentation
